#Name for the Pipeline
run-name: Test-pipeline-run ${{ github.actor }}

#Events to run pipeline
on: 
  push:
    branches: 
    - main

jobs:
  test-print-msg-job:
    runs-on: ununtu-latest
    name: test-job
      echo "Hello World"



