#Name for the Pipeline
run-name: Test-pipeline-run ${{ github.actor }}

#Events to run pipeline
on: 
  push:
    branches: 
    - main

jobs:
  test-print-msg-job:
    runs-on: ubuntu-latest
    steps:
     - name: check-directory
       run:
         pwd
     - name: listOutFiles
       run:
         ls -la
     - name: checkOutCode
       uses: actions/checkout@v3
     - name: postCheckoutRum
       run: 
         ls -la
     - name: navigateToCode
       run:
         cd my-app
     - name: my-appFileCheck
       run: ls
  npm-install-job:
    runs-on: ubuntu-latest
    steps:
     - name: npm-install
       run: npm install



