#Name for the Pipeline
run-name: Test-pipeline-run ${{ github.actor }}

#Events to run pipeline
on: 
  push:
    branches: 
    - main

jobs:
  test-print-msg-job:
    runs-on: ubuntu-latest
    steps:
     - name: check-directory
       run:
         pwd
     - name: listOutFiles
       run:
         ls -la
     - name: checkOutCode
       uses: actions/checkout@v3
     - name: npm-install
       run: |
         ls -la
         cd my-app
         npm install
     - name: build
       run: |
         cd my-app
         npm run build

