#Name for the Pipeline
run-name: Test-pipeline-run ${{ github.actor }}

#Events to run pipeline
on: 
  push:
    branches: 
    - main

jobs:
  test-print-msg-job:
    runs-on: ununtu-latest
    steps:
     - name: test-job
         echo "hello"
     - name: test-job2
         echo "World!"



